/*Acciones*/

ALTER TABLE PATROCINADOR DROP CONSTRAINT FK_USUARIO_PATROCINADOR;
ALTER TABLE CLIENTE DROP CONSTRAINT FK_USUARIO_CLIENTE;
ALTER TABLE OFRECE DROP CONSTRAINT FK_OFRECE_PATROCINADOR;
ALTER TABLE OFRECE DROP CONSTRAINT FK_OFRECE_CLIENTE;
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_CONDICION;
ALTER TABLE ENFERMEDADES DROP CONSTRAINT FK_CONDICION_ENFERMEDADES;
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_TIPO_RUTINA;
ALTER TABLE PAQUETE DROP CONSTRAINT FK_PAQUETE_TIPO_RUTINA;
ALTER TABLE IMPLEMENTOS DROP CONSTRAINT FK_IMPLEMENTO_TIPO_RUTINA;
ALTER TABLE PAQUETE_PLANENTRENAMIENTO DROP CONSTRAINT FK_PAQUETEPLANENTRENAMINETO_PAQUETE;
ALTER TABLE PAQUETE_PLANENTRENAMIENTO DROP CONSTRAINT FK_PAQUETE_PLANENTRENAMIENTO_PLAN_ENTRENAMIENTO;
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_PAQUETE;

ALTER TABLE PATROCINADOR ADD CONSTRAINT FK_USUARIO_PATROCINADOR FOREIGN KEY (nid,tipoid) REFERENCES USUARIO(nid,tipoid) ON DELETE CASCADE;
ALTER TABLE CLIENTE ADD CONSTRAINT FK_USUARIO_CLIENTE FOREIGN KEY (nid,tipoid) REFERENCES USUARIO(nid,tipoid) ON DELETE CASCADE;
ALTER TABLE OFRECE ADD CONSTRAINT FK_OFRECE_PATROCINADOR FOREIGN KEY(patrocinador_nid,patrocinador_tipoid) REFERENCES PATROCINADOR(nid,tipoid) ON DELETE CASCADE;
ALTER TABLE OFRECE ADD CONSTRAINT FK_OFRECE_CLIENTE FOREIGN KEY (cliente_nid,cliente_tipoid) REFERENCES CLIENTE(nid,tipoid) ON DELETE SET NULL;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_CONDICION FOREIGN KEY (id_condicion) REFERENCES CONDICION_FISICA(id_condicion) ON DELETE CASCADE;
ALTER TABLE ENFERMEDADES ADD CONSTRAINT FK_CONDICION_ENFERMEDADES FOREIGN KEY (id_condicion) REFERENCES CONDICION_FISICA(id_condicion) ON DELETE CASCADE;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_TIPO_RUTINA FOREIGN KEY (idtiporutina) REFERENCES TIPO_RUTINA(idtiporutina) ON DELETE CASCADE;
ALTER TABLE PAQUETE ADD CONSTRAINT FK_PAQUETE_TIPO_RUTINA FOREIGN KEY (idtiporutina) REFERENCES TIPO_RUTINA(idtiporutina) ON DELETE CASCADE;
ALTER TABLE IMPLEMENTOS ADD CONSTRAINT FK_IMPLEMENTO_TIPO_RUTINA FOREIGN KEY (idtiporutina) REFERENCES TIPO_RUTINA(idtiporutina) ON DELETE CASCADE;
ALTER TABLE PAQUETE_PLANENTRENAMIENTO ADD CONSTRAINT FK_PAQUETEPLANENTRENAMINETO_PAQUETE FOREIGN KEY (nombre) REFERENCES PAQUETE(nombre) ON DELETE CASCADE;
ALTER TABLE PAQUETE_PLANENTRENAMIENTO ADD CONSTRAINT FK_PAQUETE_PLANENTRENAMIENTO_PLAN_ENTRENAMIENTO FOREIGN KEY (codigo) REFERENCES PLAN_ENTRENAMIENTO(codigo) ON DELETE CASCADE;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PAQUETE FOREIGN KEY(paquete_nombre) REFERENCES PAQUETE(nombre) ON DELETE SET NULL;