/*XDisparadores*/

DROP TRIGGER ck_VALIDAR_FECHA_NACIMIENTO;
DROP TRIGGER ck_VALIDAR_DURACION_PAQUETE;
DROP TRIGGER CK_DESCUENTO_PAQUETE;
DROP TRIGGER CK_FECHA_REGISTRO;
DROP TRIGGER CK_CONDICION_FISICA;
DROP TRIGGER CK_TIPO_RUTINA;
DROP TRIGGER CK_Plan_entrenamiento;
DROP TRIGGER CK_RESTRICCION_CONDICION_FISICA;
DROP TRIGGER CK_RESTRICCION_TIPO_RUTINA;
DROP TRIGGER CK_RESTRICCION_PAQUETE;
DROP TRIGGER CK_RESTRICCION_PLAN_ENTRENAMIENTO;