/*AccionesOK*/

SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_USUARIO_PATROCINADOR';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_USUARIO_CLIENTE';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_OFRECE_PATROCINADOR';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_USUARIO_CLIENTE';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_USUARIO_CONDICION';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_CONDICION_ENFERMEDADES';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_USUARIO_TIPO_RUTINA';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_PAQUETE_TIPO_RUTINA';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_IMPLEMENTO_TIPO_RUTINA';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_PAQUETEPLANENTRENAMINETO_PAQUETE';
SELECT TABLE_NAME,CONSTRAINT_NAME,DELETE_RULE,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_PAQUETE_PLANENTRENAMIENTO_PLAN_ENTRENAMIENTO';