/*PK*/
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(nid,tipoid);
ALTER TABLE PATROCINADOR ADD CONSTRAINT PK_PATROCINADOR PRIMARY KEY(nid,tipoid);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(nid,tipoid);
ALTER TABLE OFRECE ADD CONSTRAINT PK_OFRECE PRIMARY KEY(cliente_nid,cliente_tipoid,patrocinador_nid,patrocinador_tipoid);
ALTER TABLE CONDICION_FISICA ADD CONSTRAINT PK_CONDICION_FISICA PRIMARY KEY(id_condicion);
ALTER TABLE ENFERMEDADES ADD CONSTRAINT PK_ENFERMEDADES PRIMARY KEY(id_enfermedad);
ALTER TABLE TIPO_RUTINA ADD CONSTRAINT PK_TIPO_RUTINA PRIMARY KEY(idtiporutina);
ALTER TABLE IMPLEMENTOS ADD CONSTRAINT PK_IMPLEMENTOS PRIMARY KEY(idtiporutina,ejercicio_nombre);
ALTER TABLE PAQUETE ADD CONSTRAINT PK_PAQUETE PRIMARY KEY(nombre);
ALTER TABLE PAQUETE_PLANENTRENAMIENTO ADD CONSTRAINT PK_PAQUETE_PLANENTRENAMIENTO PRIMARY KEY(nombre,codigo);
ALTER TABLE PLAN_ENTRENAMIENTO ADD CONSTRAINT PK_PLAN_ENTRENAMIENTO PRIMARY KEY(codigo);