/*XCRUD*/
DROP PACKAGE PC_USUARIO;
DROP PACKAGE PC_OFRECE;
DROP PACKAGE PC_CONDICION_FISICA;
DROP PACKAGE PC_TIPO_RUTINA;
DROP PACKAGE PC_PAQUETE;
DROP PACKAGE PC_PLAN_ENTRENAMIENTO;

DROP PACKAGE BODY PC_USUARIO;
DROP PACKAGE BODY PC_OFRECE;
DROP PACKAGE BODY PC_CONDICION_FISICA;
DROP PACKAGE BODY PC_TIPO_RUTINA;
DROP PACKAGE BODY PC_PAQUETE;
DROP PACKAGE BODY PC_PLAN_ENTRENAMIENTO;