/*XSeguridad*/
REVOKE EXECUTE ON PA_PATROCINADOR FROM role_patrocinador;
REVOKE EXECUTE ON pa_usuario FROM role_usuario;
REVOKE EXECUTE ON PA_GERENTE FROM role_gerente;

DROP ROLE ROLE_PATROCINADOR;
DROP ROLE ROLE_USUARIO;
DROP ROLE ROLE_GERENTE;