/*ATRIBUTOS*/

ALTER TABLE USUARIO ADD CONSTRAINT TIPOID_USUARIO CHECK(tipoid IN ('CC','TI','NIT'));
ALTER TABLE USUARIO ADD CONSTRAINT CORREO_USUARIO CHECK(correo_electronico like '%@%' and correo_electronico like '%.com');
ALTER TABLE CLIENTE ADD CONSTRAINT GENERO_CLIENTE CHECK(genero in('M','F','I'));
ALTER TABLE PATROCINADOR ADD CONSTRAINT SITIO_WEB_PATROCINADOR CHECK(SITIO_WEB LIKE 'WWW.%.COM');
ALTER TABLE OFRECE ADD CONSTRAINT OFRECE_PRODUCTO CHECK(tipo_producto in('Prendas','Suplementos','Tecnologia','Entrenamiento'));
ALTER TABLE CONDICION_FISICA ADD CONSTRAINT CONDICION_FISICA_ACTUAL CHECK(condicionactual IN ('SEDENTARIO','BAJA ACTIVIDAD','ACTIVIDAD MODERADA','ALTA ACTIVIDAD','DEPORTISTA'));
ALTER TABLE TIPO_RUTINA ADD CONSTRAINT TIPO_RUTINA_DIFICULTAD CHECK (dificultad IN ('BAJA','MEDIA','ALTA'));
ALTER TABLE TIPO_RUTINA ADD CONSTRAINT OBJETVO_RUTINA CHECK(objetivo IN('MANTENERSE EN FORMA','GANAR MUSCULO','PERDER PESO','PAUSAS ACTIVAS'));
ALTER TABLE TIPO_RUTINA ADD CONSTRAINT DURACION_RUTINA CHECK(duracion >=15 AND duracion <=90);
ALTER TABLE PAQUETE ADD CONSTRAINT DURACION_PAQUETE CHECK(duracion >= 1);
ALTER TABLE PAQUETE ADD CONSTRAINT DESCUENTO_PAQUETE CHECK(descuento IN ('TRUE','FALSE'));
ALTER TABLE PLAN_ENTRENAMIENTO ADD CONSTRAINT ENTRENAMIENTO_DIFICULTAD CHECK(dificultad IN ('BAJA','MEDIA','ALTA'));