/*XTABLAS*/

DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE PATROCINADOR CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE OFRECE CASCADE CONSTRAINTS;
DROP TABLE CONDICION_FISICA CASCADE CONSTRAINTS;
DROP TABLE ENFERMEDADES CASCADE CONSTRAINTS;
DROP TABLE TIPO_RUTINA CASCADE CONSTRAINTS;
DROP TABLE IMPLEMENTOS CASCADE CONSTRAINTS;
DROP TABLE PAQUETE CASCADE CONSTRAINTS;
DROP TABLE PAQUETE_PLANENTRENAMIENTO CASCADE CONSTRAINTS;
DROP TABLE PLAN_ENTRENAMIENTO CASCADE CONSTRAINTS;