/*Xpoblar*/

DELETE FROM USUARIO;
DELETE FROM PATROCINADOR;
DELETE FROM CLIENTE;
DELETE FROM OFRECE;
DELETE FROM CONDICION_FISICA;
DELETE FROM ENFERMEDADES;
DELETE FROM TIPO_RUTINA;
DELETE FROM IMPLEMENTOS;
DELETE FROM PAQUETE;
DELETE FROM PAQUETE_PLANENTRENAMIENTO;
DELETE FROM PLAN_ENTRENAMIENTO;